import { Dimensions, Platform, StyleSheet } from "react-native";

const height = Dimensions.get("window").height;

export const indexStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
  },
  header: {
    paddingTop: Platform.OS === "ios" ? 80 : 40,
    paddingBottom: 24,
    paddingHorizontal: 24,
    backgroundColor: "#000000",
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  greeting: {
    fontSize: 16,
    color: "#888888",
    marginBottom: 6,
    fontWeight: "400",
  },
  userName: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -1.5,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  notificationButton: {
    padding: 12,
    marginRight: 12,
    position: "relative",
    backgroundColor: "#111111",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#333333",
  },
  notificationDot: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  avatarButton: {
    padding: 2,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#333333",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#444444",
  },
  avatarText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  tabNavigation: {
    flexDirection: "row",
    backgroundColor: "#111111",
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: "#333333",
  },
  tabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  activeTabButton: {
    backgroundColor: "#FFFFFF",
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#888888",
    marginLeft: 6,
  },
  activeTabButtonText: {
    color: "#000000",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  tabContent: {
    flex: 1,
  },
  balanceSection: {
    marginHorizontal: 24,
    marginTop: 24,
    marginBottom: 32,
  },
  balanceCard: {
    backgroundColor: "#111111",
    borderRadius: 16,
    padding: 28,
    borderWidth: 1,
    borderColor: "#333333",
    position: "relative",
    overflow: "hidden",
  },
  shimmerContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
  },
  shimmerEffect: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 100,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    transform: [{ skewX: "-20deg" }],
  },
  balanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  balanceLabel: {
    fontSize: 16,
    color: "#888888",
    fontWeight: "500",
  },
  visibilityButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#222222",
    borderWidth: 1,
    borderColor: "#333333",
  },
  balanceAmountContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 32,
  },
  balanceAmount: {
    fontSize: 48,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: -2,
    marginRight: 12,
  },
  balanceStats: {
    flexDirection: "row",
    backgroundColor: "#000000",
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "#333333",
  },
  statItem: {
    flex: 1,
  },
  statIconContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    backgroundColor: "#333333",
  },
  statInfo: {
    flex: 1,
  },
  statDivider: {
    width: 1,
    height: 60,
    backgroundColor: "#333333",
    marginHorizontal: 24,
  },
  statLabel: {
    fontSize: 13,
    color: "#888888",
    marginBottom: 6,
    marginTop: 10,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    marginHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: -0.5,
  },
  addButton: {
    padding: 8,
    backgroundColor: "#000",
    borderRadius: 8,
  },
  goalsScroll: {
    paddingLeft: 24,
  },
  goalCard: {
    width: 200,
    backgroundColor: "#111111",
    borderRadius: 16,
    padding: 20,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#333333",
  },
  goalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  goalIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#333333",
    justifyContent: "center",
    alignItems: "center",
  },
  goalProgress: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "700",
  },
  goalTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 10,
  },
  goalAmount: {
    fontSize: 13,
    color: "#888888",
    marginBottom: 16,
  },
  progressBar: {
    height: 6,
    backgroundColor: "#333333",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 16,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 3,
  },
  addFundsButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  addFundsText: {
    color: "#000000",
    fontWeight: "600",
    marginLeft: 6,
    fontSize: 14,
  },
  budgetList: {
    paddingHorizontal: 24,
  },
  budgetItem: {
    backgroundColor: "#111111",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#333333",
  },
  budgetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  budgetLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  budgetIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    backgroundColor: "#333333",
  },
  budgetCategory: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  budgetAmount: {
    fontSize: 14,
    color: "#888888",
  },
  budgetRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  budgetPercentage: {
    fontSize: 16,
    fontWeight: "700",
    marginRight: 8,
  },
  budgetProgressBar: {
    height: 6,
    backgroundColor: "#333333",
    borderRadius: 3,
    overflow: "hidden",
  },
  budgetProgressFill: {
    height: "100%",
    borderRadius: 3,
  },
  quickActionsSection: {
    marginHorizontal: 24,
    marginBottom: 32,
  },
  quickActionsTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  quickActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  quickActionButton: {
    alignItems: "center",
    flex: 1,
    marginHorizontal: 6,
  },
  quickActionIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "#333333",
    borderWidth: 1,
    borderColor: "#444444",
  },
  quickActionText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "600",
    textAlign: "center",
  },
  categoriesSection: {
    marginBottom: 32,
  },
  categoriesTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 16,
    marginHorizontal: 24,
    letterSpacing: -0.5,
  },
  categoriesScroll: {
    paddingLeft: 24,
  },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: "#111111",
    borderWidth: 1,
    borderColor: "#333333",
  },
  categoryChipSelected: {
    backgroundColor: "#FFFFFF",
    borderColor: "#FFFFFF",
  },
  categoryText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
    color: "#888888",
  },
  categoryTextSelected: {
    color: "#000000",
  },
  transactionsSection: {
    marginHorizontal: 24,
  },
  transactionCount: {
    backgroundColor: "#111111",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#333333",
  },
  transactionCountText: {
    fontSize: 12,
    color: "#888888",
    fontWeight: "600",
  },
  transactionsList: {
    backgroundColor: "#111111",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#333333",
    overflow: "hidden",
  },
  transactionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#333333",
  },
  transactionLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  transactionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    backgroundColor: "#333333",
  },
  transactionInfo: {
    flex: 1,
  },
  transactionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  transactionMeta: {
    fontSize: 12,
    color: "#888888",
    fontWeight: "400",
  },
  transactionRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: "700",
    marginRight: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#111111",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 32,
    borderTopWidth: 1,
    borderColor: "#333333",
    minHeight: height * 0.6,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 32,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -0.5,
  },
  closeButton: {
    padding: 8,
    backgroundColor: "#222222",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#333333",
  },
  typeSelector: {
    flexDirection: "row",
    backgroundColor: "#222222",
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#333333",
  },
  typeButton: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  typeButtonSelected: {
    backgroundColor: "#FFFFFF",
  },
  typeButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#888888",
    marginLeft: 8,
  },
  typeButtonTextSelected: {
    color: "#000000",
  },
  input: {
    backgroundColor: "#222222",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: "#FFFFFF",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#333333",
    fontWeight: "500",
  },
  categorySelector: {
    marginBottom: 24,
  },
  categorySelectorChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    marginRight: 12,
    backgroundColor: "#222222",
    borderWidth: 1,
    borderColor: "#333333",
  },
  categorySelectorChipSelected: {
    backgroundColor: "#FFFFFF",
    borderColor: "#FFFFFF",
  },
  categorySelectorText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
    color: "#888888",
  },
  categorySelectorTextSelected: {
    color: "#000000",
  },
  submitButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
    marginRight: 8,
  },
  analyticsModalContent: {
    backgroundColor: "#111111",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 32,
    borderTopWidth: 1,
    borderColor: "#333333",
    maxHeight: height * 0.85,
  },
  analyticsSection: {
    marginBottom: 32,
  },
  analyticsSectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  analyticsItem: {
    backgroundColor: "#222222",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#333333",
  },
  analyticsItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  analyticsItemLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  analyticsItemTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginLeft: 12,
  },
  analyticsItemAmount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  analyticsProgressBar: {
    height: 6,
    backgroundColor: "#333333",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 8,
  },
  analyticsProgressFill: {
    height: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 3,
  },
  analyticsPercentage: {
    fontSize: 12,
    color: "#888888",
    textAlign: "right",
  },
  healthScoreContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#222222",
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "#333333",
  },
  healthScoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 20,
  },
  healthScoreText: {
    fontSize: 24,
    fontWeight: "800",
    color: "#000000",
  },
  healthScoreLabel: {
    fontSize: 12,
    color: "#000000",
    fontWeight: "600",
  },
  healthScoreInfo: {
    flex: 1,
  },
  healthScoreTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 6,
  },
  healthScoreDescription: {
    fontSize: 14,
    color: "#888888",
    lineHeight: 20,
  },
  trendChart: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    backgroundColor: "#222222",
    borderRadius: 12,
    padding: 20,
    height: 150,
    borderWidth: 1,
    borderColor: "#333333",
  },
  trendBarContainer: {
    alignItems: "center",
    flex: 1,
  },
  trendBar: {
    width: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginBottom: 8,
    minHeight: 20,
  },
  trendDay: {
    fontSize: 12,
    color: "#888888",
    fontWeight: "600",
  },
});
